### ISSUE TITLE
很好用，但是能不能打印日志

### ISSUE THREAD

**Issue by huiget** [gwy15/tracker-proxy#1]
确实好用。

但是用的时候不知道支不支持代理用 http，运行的时候也没有打印看不出来，最后尝试了多种组合才跑起来了。

所以（如果有）下个版本，能不能加个日志。或者其实现在已经有日志了，但是 release 版不会打印？没学过 rust。。

**Comment by gwy15** [comment]
现在是有日志的，但是默认级别是error，设置环境变量 RUST_LOG=info或者debug就可以了

**Comment by huiget** [comment]
> 现在是有日志的，但是默认级别是error，设置环境变量 RUST_LOG=info或者debug就可以了

Great!
