### ISSUE TITLE
在 win 10 上遇到了连接问题，重新 build 问题不见了

### ISSUE THREAD

**Issue by huiget** [gwy15/tracker-proxy#2]
![image](https://user-images.githubusercontent.com/8924054/124370370-72e31300-dca9-11eb-8d35-31fcdce5a055.png)
可以确定是 tracker-proxy 的问题，这个是 debug 日志。

不知道能不能查出什么问题来，查不出也无所谓。 thx。

**Comment by gwy15** [comment]
看不出来啥问题，我新发一个release吧
