### ISSUE TITLE
冒昧打扰, 有种子有用户就是没有速度(带多图)

### ISSUE THREAD

**Issue by KesaubeEire** [gwy15/tracker-proxy#3]
我配了 ipv6 的vps , 在 远端布置了 浏览器 transmission 客户端 , 可以下 byr 没问题  
但是 vps 容量太小 , 想在电脑上下byr的资源  
看到您的教程十分激动 , 但是失败了 , 下面是一堆截图   
您的程序能跑起来 , 我本地 localhost:8080 是有东西的   
但是我就是 有种子 有用户 没速度 , 很无助   
若您有时间感谢您回复谢谢 !  
![本地v2ray客户端.png](https://i.loli.net/2021/11/12/r1uvwnPEsiaTYBZ.png)
![本地命令行.png](https://i.loli.net/2021/11/12/TeU7WAH3VEvb2ih.png)
![本地uTorrent.png](https://i.loli.net/2021/11/12/OmfgJEj49KIRezh.png)

**Comment by gwy15** [comment]
log 可以通过设置环境变量开启
```powershell
$env:RUST_LOG='debug'
```

如果有用户没速度，看一下下面的 用户 tab，可能是没法连接上用户，原因很多，可能是你本地没有 ipv6 网络。这个只代理 tracker，是不会代理网络的
